.TH JAWS 1 "2 February 2021" "version 0.1.0"
.SH NAME
jaws - an invisible, stack-based, interpreted programming language
.SH SYNOPSIS
.B jaws [ -h ]
.B [ -d 
.I debuglevel
.B ] 
.I infile
.SH DESCRIPTION
.B Jaws
(Just Another WhiteSpace) is an esoteric interpreted programming language based on another, called whitespace, with more functionality. Jaws is an imperative, stack based language. The name Jaws is an acronym, but the word itself was also intended to hold meaning because the code, being invisible to the human eye, is like a threat hidden beneath the surface.
.PP
Like whitespace, the only lexical tokens in Jaws are \fISpace \fR(ASCII 32), \fITab \fR(ASCII 9), and \fI Linefeed \fR(ASCII 10). The original choice to use linefeed only and not carraige return was to avoid DOS/Unix conversion problems.
.PP
To see the language specification for Jaws, go to:
.br
https://github.com/doctormay6/jaws/tree/main/jawsVM
.SH OPTIONS
.IP -h
Show usage for jaws
.IP "-d \fIdebuglevel"
.R Specifies debug level. 0 is default. 1 prints instructions as they are executed. 2 also prints instructions as they are parsed.
.SH BUGS
Networking is currently not working on the Windows platform.
.SH AUTHOR
This program was written by C.J. May (doctormay6[at]gmail[dot]com).
